# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: baseDocument.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import workspace_pb2 as workspace__pb2
import basicTypes_pb2 as basicTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='baseDocument.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x62\x61seDocument.proto\x12\x07rv.data\x1a\x0fworkspace.proto\x1a\x10\x62\x61sicTypes.proto\"\x9e\x01\n\x08\x44ocument\x12\x32\n\x10\x61pplication_info\x18\x01 \x01(\x0b\x32\x18.rv.data.ApplicationInfo\x12\x1b\n\x04uuid\x18\x02 \x01(\x0b\x32\r.rv.data.UUID\x12\x1a\n\x12uses_relative_urls\x18\x03 \x01(\x08\x12%\n\tworkspace\x18\n \x01(\x0b\x32\x12.rv.data.Workspace\"\x8e\x01\n\tCacheInfo\x12\x1b\n\x04uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12-\n\x13\x61pplication_version\x18\x02 \x01(\x0b\x32\x10.rv.data.Version\x12\x19\n\x03url\x18\x03 \x01(\x0b\x32\x0c.rv.data.URL\x12\x1a\n\x12last_modified_date\x18\x04 \x01(\x01\"\xd7\x04\n\x10PVPDocumentState\x12\x41\n\x10primary_playlist\x18\x01 \x01(\x0b\x32\'.rv.data.PVPDocumentState.PlaylistState\x12\x43\n\x12\x61lternate_playlist\x18\x02 \x01(\x0b\x32\'.rv.data.PVPDocumentState.PlaylistState\x12\"\n\x1aplaylist_split_is_vertical\x18\x03 \x01(\x08\x12%\n\x0etargeted_layer\x18\x04 \x01(\x0b\x32\r.rv.data.UUID\x12%\n\x0eselected_layer\x18\x05 \x01(\x0b\x32\r.rv.data.UUID\x12#\n\x0clocked_layer\x18\x06 \x01(\x0b\x32\r.rv.data.UUID\x12!\n\x19live_video_playlist_scale\x18\x07 \x01(\x01\x12#\n\x1bsplit_view_divider_position\x18\x08 \x01(\x01\x1a\xdb\x01\n\rPlaylistState\x12\x1b\n\x04uuid\x18\x02 \x01(\x0b\x32\r.rv.data.UUID\x12\x42\n\x06layout\x18\x03 \x01(\x0e\x32\x32.rv.data.PVPDocumentState.PlaylistState.LayoutType\x12\x12\n\nitem_scale\x18\x04 \x01(\x01\"U\n\nLayoutType\x12\x13\n\x0fLAYOUT_TYPE_CUE\x10\x00\x12\x16\n\x12LAYOUT_TYPE_ACTION\x10\x01\x12\x1a\n\x16LAYOUT_TYPE_LIVE_VIDEO\x10\x02\x62\x06proto3'
  ,
  dependencies=[workspace__pb2.DESCRIPTOR,basicTypes__pb2.DESCRIPTOR,])



_PVPDOCUMENTSTATE_PLAYLISTSTATE_LAYOUTTYPE = _descriptor.EnumDescriptor(
  name='LayoutType',
  full_name='rv.data.PVPDocumentState.PlaylistState.LayoutType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LAYOUT_TYPE_CUE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LAYOUT_TYPE_ACTION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LAYOUT_TYPE_LIVE_VIDEO', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=887,
  serialized_end=972,
)
_sym_db.RegisterEnumDescriptor(_PVPDOCUMENTSTATE_PLAYLISTSTATE_LAYOUTTYPE)


_DOCUMENT = _descriptor.Descriptor(
  name='Document',
  full_name='rv.data.Document',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='application_info', full_name='rv.data.Document.application_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='rv.data.Document.uuid', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uses_relative_urls', full_name='rv.data.Document.uses_relative_urls', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='workspace', full_name='rv.data.Document.workspace', index=3,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=225,
)


_CACHEINFO = _descriptor.Descriptor(
  name='CacheInfo',
  full_name='rv.data.CacheInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='rv.data.CacheInfo.uuid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='application_version', full_name='rv.data.CacheInfo.application_version', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='rv.data.CacheInfo.url', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_modified_date', full_name='rv.data.CacheInfo.last_modified_date', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=370,
)


_PVPDOCUMENTSTATE_PLAYLISTSTATE = _descriptor.Descriptor(
  name='PlaylistState',
  full_name='rv.data.PVPDocumentState.PlaylistState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='rv.data.PVPDocumentState.PlaylistState.uuid', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='layout', full_name='rv.data.PVPDocumentState.PlaylistState.layout', index=1,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item_scale', full_name='rv.data.PVPDocumentState.PlaylistState.item_scale', index=2,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PVPDOCUMENTSTATE_PLAYLISTSTATE_LAYOUTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=753,
  serialized_end=972,
)

_PVPDOCUMENTSTATE = _descriptor.Descriptor(
  name='PVPDocumentState',
  full_name='rv.data.PVPDocumentState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='primary_playlist', full_name='rv.data.PVPDocumentState.primary_playlist', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alternate_playlist', full_name='rv.data.PVPDocumentState.alternate_playlist', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='playlist_split_is_vertical', full_name='rv.data.PVPDocumentState.playlist_split_is_vertical', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='targeted_layer', full_name='rv.data.PVPDocumentState.targeted_layer', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='selected_layer', full_name='rv.data.PVPDocumentState.selected_layer', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='locked_layer', full_name='rv.data.PVPDocumentState.locked_layer', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='live_video_playlist_scale', full_name='rv.data.PVPDocumentState.live_video_playlist_scale', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='split_view_divider_position', full_name='rv.data.PVPDocumentState.split_view_divider_position', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PVPDOCUMENTSTATE_PLAYLISTSTATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=972,
)

_DOCUMENT.fields_by_name['application_info'].message_type = basicTypes__pb2._APPLICATIONINFO
_DOCUMENT.fields_by_name['uuid'].message_type = basicTypes__pb2._UUID
_DOCUMENT.fields_by_name['workspace'].message_type = workspace__pb2._WORKSPACE
_CACHEINFO.fields_by_name['uuid'].message_type = basicTypes__pb2._UUID
_CACHEINFO.fields_by_name['application_version'].message_type = basicTypes__pb2._VERSION
_CACHEINFO.fields_by_name['url'].message_type = basicTypes__pb2._URL
_PVPDOCUMENTSTATE_PLAYLISTSTATE.fields_by_name['uuid'].message_type = basicTypes__pb2._UUID
_PVPDOCUMENTSTATE_PLAYLISTSTATE.fields_by_name['layout'].enum_type = _PVPDOCUMENTSTATE_PLAYLISTSTATE_LAYOUTTYPE
_PVPDOCUMENTSTATE_PLAYLISTSTATE.containing_type = _PVPDOCUMENTSTATE
_PVPDOCUMENTSTATE_PLAYLISTSTATE_LAYOUTTYPE.containing_type = _PVPDOCUMENTSTATE_PLAYLISTSTATE
_PVPDOCUMENTSTATE.fields_by_name['primary_playlist'].message_type = _PVPDOCUMENTSTATE_PLAYLISTSTATE
_PVPDOCUMENTSTATE.fields_by_name['alternate_playlist'].message_type = _PVPDOCUMENTSTATE_PLAYLISTSTATE
_PVPDOCUMENTSTATE.fields_by_name['targeted_layer'].message_type = basicTypes__pb2._UUID
_PVPDOCUMENTSTATE.fields_by_name['selected_layer'].message_type = basicTypes__pb2._UUID
_PVPDOCUMENTSTATE.fields_by_name['locked_layer'].message_type = basicTypes__pb2._UUID
DESCRIPTOR.message_types_by_name['Document'] = _DOCUMENT
DESCRIPTOR.message_types_by_name['CacheInfo'] = _CACHEINFO
DESCRIPTOR.message_types_by_name['PVPDocumentState'] = _PVPDOCUMENTSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Document = _reflection.GeneratedProtocolMessageType('Document', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENT,
  '__module__' : 'baseDocument_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.Document)
  })
_sym_db.RegisterMessage(Document)

CacheInfo = _reflection.GeneratedProtocolMessageType('CacheInfo', (_message.Message,), {
  'DESCRIPTOR' : _CACHEINFO,
  '__module__' : 'baseDocument_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.CacheInfo)
  })
_sym_db.RegisterMessage(CacheInfo)

PVPDocumentState = _reflection.GeneratedProtocolMessageType('PVPDocumentState', (_message.Message,), {

  'PlaylistState' : _reflection.GeneratedProtocolMessageType('PlaylistState', (_message.Message,), {
    'DESCRIPTOR' : _PVPDOCUMENTSTATE_PLAYLISTSTATE,
    '__module__' : 'baseDocument_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.PVPDocumentState.PlaylistState)
    })
  ,
  'DESCRIPTOR' : _PVPDOCUMENTSTATE,
  '__module__' : 'baseDocument_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.PVPDocumentState)
  })
_sym_db.RegisterMessage(PVPDocumentState)
_sym_db.RegisterMessage(PVPDocumentState.PlaylistState)


# @@protoc_insertion_point(module_scope)
