# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calendar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2
import timestamp_pb2 as timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='calendar.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x63\x61lendar.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\x1a\x0ftimestamp.proto\"\xba\x06\n\x08\x43\x61lendar\x12\'\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x17.rv.data.Calendar.Event\x12\x0e\n\x06\x61\x63tive\x18\x02 \x01(\x08\x1a\xf4\x05\n\x05\x45vent\x12\x1b\n\x04uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12 \n\x04\x64\x61te\x18\x04 \x01(\x0b\x32\x12.rv.data.Timestamp\x12:\n\x0frecurrence_days\x18\x05 \x03(\x0e\x32!.rv.data.Calendar.Event.DayOfWeek\x12\x31\n\x15recurrence_limit_date\x18\x06 \x01(\x0b\x32\x12.rv.data.Timestamp\x12\x35\n\x19recurrence_excluded_dates\x18\x07 \x03(\x0b\x32\x12.rv.data.Timestamp\x12.\n\x06\x61\x63tion\x18\x08 \x01(\x0b\x32\x1e.rv.data.Calendar.Event.Action\x1a\xdb\x01\n\x06\x41\x63tion\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x1b\n\x04uuid\x18\x02 \x01(\x0b\x32\r.rv.data.UUID\x12;\n\x08playlist\x18\x03 \x01(\x0b\x32\'.rv.data.Calendar.Event.Action.PlaylistH\x00\x1a[\n\x08Playlist\x12$\n\rplaylist_uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12)\n\x12playlist_item_uuid\x18\x02 \x01(\x0b\x32\r.rv.data.UUIDB\x0c\n\nActionType\"\xd4\x01\n\tDayOfWeek\x12\x17\n\x13\x44\x41Y_OF_WEEK_UNKNOWN\x10\x00\x12\x16\n\x12\x44\x41Y_OF_WEEK_SUNDAY\x10\x01\x12\x16\n\x12\x44\x41Y_OF_WEEK_MONDAY\x10\x02\x12\x17\n\x13\x44\x41Y_OF_WEEK_TUESDAY\x10\x03\x12\x19\n\x15\x44\x41Y_OF_WEEK_WEDNESDAY\x10\x04\x12\x18\n\x14\x44\x41Y_OF_WEEK_THURSDAY\x10\x05\x12\x16\n\x12\x44\x41Y_OF_WEEK_FRIDAY\x10\x06\x12\x18\n\x14\x44\x41Y_OF_WEEK_SATURDAY\x10\x07\x62\x06proto3'
  ,
  dependencies=[basicTypes__pb2.DESCRIPTOR,timestamp__pb2.DESCRIPTOR,])



_CALENDAR_EVENT_DAYOFWEEK = _descriptor.EnumDescriptor(
  name='DayOfWeek',
  full_name='rv.data.Calendar.Event.DayOfWeek',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DAY_OF_WEEK_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DAY_OF_WEEK_SUNDAY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DAY_OF_WEEK_MONDAY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DAY_OF_WEEK_TUESDAY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DAY_OF_WEEK_WEDNESDAY', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DAY_OF_WEEK_THURSDAY', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DAY_OF_WEEK_FRIDAY', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DAY_OF_WEEK_SATURDAY', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=677,
  serialized_end=889,
)
_sym_db.RegisterEnumDescriptor(_CALENDAR_EVENT_DAYOFWEEK)


_CALENDAR_EVENT_ACTION_PLAYLIST = _descriptor.Descriptor(
  name='Playlist',
  full_name='rv.data.Calendar.Event.Action.Playlist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='playlist_uuid', full_name='rv.data.Calendar.Event.Action.Playlist.playlist_uuid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='playlist_item_uuid', full_name='rv.data.Calendar.Event.Action.Playlist.playlist_item_uuid', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=569,
  serialized_end=660,
)

_CALENDAR_EVENT_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='rv.data.Calendar.Event.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='rv.data.Calendar.Event.Action.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='rv.data.Calendar.Event.Action.uuid', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='playlist', full_name='rv.data.Calendar.Event.Action.playlist', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CALENDAR_EVENT_ACTION_PLAYLIST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='ActionType', full_name='rv.data.Calendar.Event.Action.ActionType',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=455,
  serialized_end=674,
)

_CALENDAR_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='rv.data.Calendar.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='rv.data.Calendar.Event.uuid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='rv.data.Calendar.Event.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='rv.data.Calendar.Event.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='rv.data.Calendar.Event.date', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recurrence_days', full_name='rv.data.Calendar.Event.recurrence_days', index=4,
      number=5, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recurrence_limit_date', full_name='rv.data.Calendar.Event.recurrence_limit_date', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recurrence_excluded_dates', full_name='rv.data.Calendar.Event.recurrence_excluded_dates', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='rv.data.Calendar.Event.action', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CALENDAR_EVENT_ACTION, ],
  enum_types=[
    _CALENDAR_EVENT_DAYOFWEEK,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=889,
)

_CALENDAR = _descriptor.Descriptor(
  name='Calendar',
  full_name='rv.data.Calendar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='events', full_name='rv.data.Calendar.events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='active', full_name='rv.data.Calendar.active', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CALENDAR_EVENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=889,
)

_CALENDAR_EVENT_ACTION_PLAYLIST.fields_by_name['playlist_uuid'].message_type = basicTypes__pb2._UUID
_CALENDAR_EVENT_ACTION_PLAYLIST.fields_by_name['playlist_item_uuid'].message_type = basicTypes__pb2._UUID
_CALENDAR_EVENT_ACTION_PLAYLIST.containing_type = _CALENDAR_EVENT_ACTION
_CALENDAR_EVENT_ACTION.fields_by_name['uuid'].message_type = basicTypes__pb2._UUID
_CALENDAR_EVENT_ACTION.fields_by_name['playlist'].message_type = _CALENDAR_EVENT_ACTION_PLAYLIST
_CALENDAR_EVENT_ACTION.containing_type = _CALENDAR_EVENT
_CALENDAR_EVENT_ACTION.oneofs_by_name['ActionType'].fields.append(
  _CALENDAR_EVENT_ACTION.fields_by_name['playlist'])
_CALENDAR_EVENT_ACTION.fields_by_name['playlist'].containing_oneof = _CALENDAR_EVENT_ACTION.oneofs_by_name['ActionType']
_CALENDAR_EVENT.fields_by_name['uuid'].message_type = basicTypes__pb2._UUID
_CALENDAR_EVENT.fields_by_name['date'].message_type = timestamp__pb2._TIMESTAMP
_CALENDAR_EVENT.fields_by_name['recurrence_days'].enum_type = _CALENDAR_EVENT_DAYOFWEEK
_CALENDAR_EVENT.fields_by_name['recurrence_limit_date'].message_type = timestamp__pb2._TIMESTAMP
_CALENDAR_EVENT.fields_by_name['recurrence_excluded_dates'].message_type = timestamp__pb2._TIMESTAMP
_CALENDAR_EVENT.fields_by_name['action'].message_type = _CALENDAR_EVENT_ACTION
_CALENDAR_EVENT.containing_type = _CALENDAR
_CALENDAR_EVENT_DAYOFWEEK.containing_type = _CALENDAR_EVENT
_CALENDAR.fields_by_name['events'].message_type = _CALENDAR_EVENT
DESCRIPTOR.message_types_by_name['Calendar'] = _CALENDAR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Calendar = _reflection.GeneratedProtocolMessageType('Calendar', (_message.Message,), {

  'Event' : _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {

    'Action' : _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {

      'Playlist' : _reflection.GeneratedProtocolMessageType('Playlist', (_message.Message,), {
        'DESCRIPTOR' : _CALENDAR_EVENT_ACTION_PLAYLIST,
        '__module__' : 'calendar_pb2'
        # @@protoc_insertion_point(class_scope:rv.data.Calendar.Event.Action.Playlist)
        })
      ,
      'DESCRIPTOR' : _CALENDAR_EVENT_ACTION,
      '__module__' : 'calendar_pb2'
      # @@protoc_insertion_point(class_scope:rv.data.Calendar.Event.Action)
      })
    ,
    'DESCRIPTOR' : _CALENDAR_EVENT,
    '__module__' : 'calendar_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.Calendar.Event)
    })
  ,
  'DESCRIPTOR' : _CALENDAR,
  '__module__' : 'calendar_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.Calendar)
  })
_sym_db.RegisterMessage(Calendar)
_sym_db.RegisterMessage(Calendar.Event)
_sym_db.RegisterMessage(Calendar.Event.Action)
_sym_db.RegisterMessage(Calendar.Event.Action.Playlist)


# @@protoc_insertion_point(module_scope)
