# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ccli.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2
import template_pb2 as template__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ccli.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nccli.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\x1a\x0etemplate.proto\"\xe8\x02\n\x0c\x43\x43LIDocument\x12\x32\n\x10\x61pplication_info\x18\x01 \x01(\x0b\x32\x18.rv.data.ApplicationInfo\x12\x1b\n\x13\x65nable_ccli_display\x18\x02 \x01(\x08\x12\x14\n\x0c\x63\x63li_license\x18\x03 \x01(\t\x12\x37\n\x0c\x64isplay_type\x18\x04 \x01(\x0e\x32!.rv.data.CCLIDocument.DisplayType\x12)\n\x08template\x18\x05 \x01(\x0b\x32\x17.rv.data.Template.Slide\"\x8c\x01\n\x0b\x44isplayType\x12\x1c\n\x18\x44ISPLAY_TYPE_FIRST_SLIDE\x10\x00\x12\x1b\n\x17\x44ISPLAY_TYPE_LAST_SLIDE\x10\x01\x12%\n!DISPLAY_TYPE_FIRST_AND_LAST_SLIDE\x10\x02\x12\x1b\n\x17\x44ISPLAY_TYPE_ALL_SLIDES\x10\x03\x62\x06proto3'
  ,
  dependencies=[basicTypes__pb2.DESCRIPTOR,template__pb2.DESCRIPTOR,])



_CCLIDOCUMENT_DISPLAYTYPE = _descriptor.EnumDescriptor(
  name='DisplayType',
  full_name='rv.data.CCLIDocument.DisplayType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISPLAY_TYPE_FIRST_SLIDE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISPLAY_TYPE_LAST_SLIDE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISPLAY_TYPE_FIRST_AND_LAST_SLIDE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISPLAY_TYPE_ALL_SLIDES', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=278,
  serialized_end=418,
)
_sym_db.RegisterEnumDescriptor(_CCLIDOCUMENT_DISPLAYTYPE)


_CCLIDOCUMENT = _descriptor.Descriptor(
  name='CCLIDocument',
  full_name='rv.data.CCLIDocument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='application_info', full_name='rv.data.CCLIDocument.application_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable_ccli_display', full_name='rv.data.CCLIDocument.enable_ccli_display', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ccli_license', full_name='rv.data.CCLIDocument.ccli_license', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='display_type', full_name='rv.data.CCLIDocument.display_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='template', full_name='rv.data.CCLIDocument.template', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CCLIDOCUMENT_DISPLAYTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=418,
)

_CCLIDOCUMENT.fields_by_name['application_info'].message_type = basicTypes__pb2._APPLICATIONINFO
_CCLIDOCUMENT.fields_by_name['display_type'].enum_type = _CCLIDOCUMENT_DISPLAYTYPE
_CCLIDOCUMENT.fields_by_name['template'].message_type = template__pb2._TEMPLATE_SLIDE
_CCLIDOCUMENT_DISPLAYTYPE.containing_type = _CCLIDOCUMENT
DESCRIPTOR.message_types_by_name['CCLIDocument'] = _CCLIDOCUMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CCLIDocument = _reflection.GeneratedProtocolMessageType('CCLIDocument', (_message.Message,), {
  'DESCRIPTOR' : _CCLIDOCUMENT,
  '__module__' : 'ccli_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.CCLIDocument)
  })
_sym_db.RegisterMessage(CCLIDocument)


# @@protoc_insertion_point(module_scope)
