# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: labels.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import action_pb2 as action__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='labels.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0clabels.proto\x12\x07rv.data\x1a\x0c\x61\x63tion.proto\":\n\x11ProLabelsDocument\x12%\n\x06labels\x18\x01 \x03(\x0b\x32\x15.rv.data.Action.Labelb\x06proto3'
  ,
  dependencies=[action__pb2.DESCRIPTOR,])




_PROLABELSDOCUMENT = _descriptor.Descriptor(
  name='ProLabelsDocument',
  full_name='rv.data.ProLabelsDocument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='labels', full_name='rv.data.ProLabelsDocument.labels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=97,
)

_PROLABELSDOCUMENT.fields_by_name['labels'].message_type = action__pb2._ACTION_LABEL
DESCRIPTOR.message_types_by_name['ProLabelsDocument'] = _PROLABELSDOCUMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProLabelsDocument = _reflection.GeneratedProtocolMessageType('ProLabelsDocument', (_message.Message,), {
  'DESCRIPTOR' : _PROLABELSDOCUMENT,
  '__module__' : 'labels_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.ProLabelsDocument)
  })
_sym_db.RegisterMessage(ProLabelsDocument)


# @@protoc_insertion_point(module_scope)
