# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='library.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rlibrary.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\"\x8c\x02\n\x07Library\x12\x19\n\x03url\x18\x01 \x01(\x0b\x32\x0c.rv.data.URL\x12\x38\n\x0flibraryChildren\x18\x02 \x01(\x0b\x32\x1d.rv.data.Library.LibraryArrayH\x00\x12\x35\n\x0clibraryItems\x18\x03 \x01(\x0b\x32\x1d.rv.data.Library.LibraryItemsH\x00\x1a\x33\n\x0cLibraryArray\x12#\n\tlibraries\x18\x01 \x03(\x0b\x32\x10.rv.data.Library\x1a\x33\n\x0cLibraryItems\x12#\n\x05items\x18\x01 \x03(\x0b\x32\x14.rv.data.LibraryItemB\x0b\n\tChildType\"(\n\x0bLibraryItem\x12\x19\n\x03url\x18\x01 \x01(\x0b\x32\x0c.rv.data.URLb\x06proto3'
  ,
  dependencies=[basicTypes__pb2.DESCRIPTOR,])




_LIBRARY_LIBRARYARRAY = _descriptor.Descriptor(
  name='LibraryArray',
  full_name='rv.data.Library.LibraryArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='libraries', full_name='rv.data.Library.LibraryArray.libraries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=247,
)

_LIBRARY_LIBRARYITEMS = _descriptor.Descriptor(
  name='LibraryItems',
  full_name='rv.data.Library.LibraryItems',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='rv.data.Library.LibraryItems.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=300,
)

_LIBRARY = _descriptor.Descriptor(
  name='Library',
  full_name='rv.data.Library',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='rv.data.Library.url', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='libraryChildren', full_name='rv.data.Library.libraryChildren', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='libraryItems', full_name='rv.data.Library.libraryItems', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_LIBRARY_LIBRARYARRAY, _LIBRARY_LIBRARYITEMS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='ChildType', full_name='rv.data.Library.ChildType',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=45,
  serialized_end=313,
)


_LIBRARYITEM = _descriptor.Descriptor(
  name='LibraryItem',
  full_name='rv.data.LibraryItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='rv.data.LibraryItem.url', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=355,
)

_LIBRARY_LIBRARYARRAY.fields_by_name['libraries'].message_type = _LIBRARY
_LIBRARY_LIBRARYARRAY.containing_type = _LIBRARY
_LIBRARY_LIBRARYITEMS.fields_by_name['items'].message_type = _LIBRARYITEM
_LIBRARY_LIBRARYITEMS.containing_type = _LIBRARY
_LIBRARY.fields_by_name['url'].message_type = basicTypes__pb2._URL
_LIBRARY.fields_by_name['libraryChildren'].message_type = _LIBRARY_LIBRARYARRAY
_LIBRARY.fields_by_name['libraryItems'].message_type = _LIBRARY_LIBRARYITEMS
_LIBRARY.oneofs_by_name['ChildType'].fields.append(
  _LIBRARY.fields_by_name['libraryChildren'])
_LIBRARY.fields_by_name['libraryChildren'].containing_oneof = _LIBRARY.oneofs_by_name['ChildType']
_LIBRARY.oneofs_by_name['ChildType'].fields.append(
  _LIBRARY.fields_by_name['libraryItems'])
_LIBRARY.fields_by_name['libraryItems'].containing_oneof = _LIBRARY.oneofs_by_name['ChildType']
_LIBRARYITEM.fields_by_name['url'].message_type = basicTypes__pb2._URL
DESCRIPTOR.message_types_by_name['Library'] = _LIBRARY
DESCRIPTOR.message_types_by_name['LibraryItem'] = _LIBRARYITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Library = _reflection.GeneratedProtocolMessageType('Library', (_message.Message,), {

  'LibraryArray' : _reflection.GeneratedProtocolMessageType('LibraryArray', (_message.Message,), {
    'DESCRIPTOR' : _LIBRARY_LIBRARYARRAY,
    '__module__' : 'library_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.Library.LibraryArray)
    })
  ,

  'LibraryItems' : _reflection.GeneratedProtocolMessageType('LibraryItems', (_message.Message,), {
    'DESCRIPTOR' : _LIBRARY_LIBRARYITEMS,
    '__module__' : 'library_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.Library.LibraryItems)
    })
  ,
  'DESCRIPTOR' : _LIBRARY,
  '__module__' : 'library_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.Library)
  })
_sym_db.RegisterMessage(Library)
_sym_db.RegisterMessage(Library.LibraryArray)
_sym_db.RegisterMessage(Library.LibraryItems)

LibraryItem = _reflection.GeneratedProtocolMessageType('LibraryItem', (_message.Message,), {
  'DESCRIPTOR' : _LIBRARYITEM,
  '__module__' : 'library_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.LibraryItem)
  })
_sym_db.RegisterMessage(LibraryItem)


# @@protoc_insertion_point(module_scope)
