# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: liveVideoPlaylist.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2
import action_pb2 as action__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='liveVideoPlaylist.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17liveVideoPlaylist.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\x1a\x0c\x61\x63tion.proto\"~\n\x11LiveVideoPlaylist\x12 \n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32\x0f.rv.data.Action\x12*\n\x13targeted_layer_UUID\x18\x02 \x01(\x0b\x32\r.rv.data.UUID\x12\x1b\n\x04uuid\x18\x03 \x01(\x0b\x32\r.rv.data.UUIDb\x06proto3'
  ,
  dependencies=[basicTypes__pb2.DESCRIPTOR,action__pb2.DESCRIPTOR,])




_LIVEVIDEOPLAYLIST = _descriptor.Descriptor(
  name='LiveVideoPlaylist',
  full_name='rv.data.LiveVideoPlaylist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='actions', full_name='rv.data.LiveVideoPlaylist.actions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='targeted_layer_UUID', full_name='rv.data.LiveVideoPlaylist.targeted_layer_UUID', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='rv.data.LiveVideoPlaylist.uuid', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=194,
)

_LIVEVIDEOPLAYLIST.fields_by_name['actions'].message_type = action__pb2._ACTION
_LIVEVIDEOPLAYLIST.fields_by_name['targeted_layer_UUID'].message_type = basicTypes__pb2._UUID
_LIVEVIDEOPLAYLIST.fields_by_name['uuid'].message_type = basicTypes__pb2._UUID
DESCRIPTOR.message_types_by_name['LiveVideoPlaylist'] = _LIVEVIDEOPLAYLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LiveVideoPlaylist = _reflection.GeneratedProtocolMessageType('LiveVideoPlaylist', (_message.Message,), {
  'DESCRIPTOR' : _LIVEVIDEOPLAYLIST,
  '__module__' : 'liveVideoPlaylist_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.LiveVideoPlaylist)
  })
_sym_db.RegisterMessage(LiveVideoPlaylist)


# @@protoc_insertion_point(module_scope)
