# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proAudienceLook.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proAudienceLook.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15proAudienceLook.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\"\xc1\x04\n\x0fProAudienceLook\x12\x1b\n\x04uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12\x0c\n\x04name\x18\x02 \x01(\t\x12<\n\x0cscreen_looks\x18\x03 \x03(\x0b\x32&.rv.data.ProAudienceLook.ProScreenLook\x12)\n\x12original_look_uuid\x18\x04 \x01(\x0b\x32\r.rv.data.UUID\x1a\x99\x03\n\rProScreenLook\x12&\n\x0fpro_screen_uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12\x15\n\rprops_enabled\x18\x02 \x01(\x08\x12\x1a\n\x12live_video_enabled\x18\x03 \x01(\x08\x12\'\n\x1fpresentation_background_enabled\x18\x04 \x01(\x08\x12\x31\n\x1btemplate_document_file_path\x18\x05 \x01(\x0b\x32\x0c.rv.data.URL\x12*\n\x13template_slide_uuid\x18\x06 \x01(\x0b\x32\r.rv.data.UUID\x12\'\n\x1fpresentation_foreground_enabled\x18\x07 \x01(\x08\x12 \n\tmask_uuid\x18\x08 \x01(\x0b\x32\r.rv.data.UUID\x12\x1d\n\x15\x61nnouncements_enabled\x18\t \x01(\x08\x12\x1b\n\x13props_layer_enabled\x18\n \x01(\x08\x12\x1e\n\x16messages_layer_enabled\x18\x0b \x01(\x08\x62\x06proto3'
  ,
  dependencies=[basicTypes__pb2.DESCRIPTOR,])




_PROAUDIENCELOOK_PROSCREENLOOK = _descriptor.Descriptor(
  name='ProScreenLook',
  full_name='rv.data.ProAudienceLook.ProScreenLook',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pro_screen_uuid', full_name='rv.data.ProAudienceLook.ProScreenLook.pro_screen_uuid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='props_enabled', full_name='rv.data.ProAudienceLook.ProScreenLook.props_enabled', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='live_video_enabled', full_name='rv.data.ProAudienceLook.ProScreenLook.live_video_enabled', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='presentation_background_enabled', full_name='rv.data.ProAudienceLook.ProScreenLook.presentation_background_enabled', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='template_document_file_path', full_name='rv.data.ProAudienceLook.ProScreenLook.template_document_file_path', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='template_slide_uuid', full_name='rv.data.ProAudienceLook.ProScreenLook.template_slide_uuid', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='presentation_foreground_enabled', full_name='rv.data.ProAudienceLook.ProScreenLook.presentation_foreground_enabled', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mask_uuid', full_name='rv.data.ProAudienceLook.ProScreenLook.mask_uuid', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='announcements_enabled', full_name='rv.data.ProAudienceLook.ProScreenLook.announcements_enabled', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='props_layer_enabled', full_name='rv.data.ProAudienceLook.ProScreenLook.props_layer_enabled', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='messages_layer_enabled', full_name='rv.data.ProAudienceLook.ProScreenLook.messages_layer_enabled', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=630,
)

_PROAUDIENCELOOK = _descriptor.Descriptor(
  name='ProAudienceLook',
  full_name='rv.data.ProAudienceLook',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='rv.data.ProAudienceLook.uuid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='rv.data.ProAudienceLook.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='screen_looks', full_name='rv.data.ProAudienceLook.screen_looks', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='original_look_uuid', full_name='rv.data.ProAudienceLook.original_look_uuid', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PROAUDIENCELOOK_PROSCREENLOOK, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=630,
)

_PROAUDIENCELOOK_PROSCREENLOOK.fields_by_name['pro_screen_uuid'].message_type = basicTypes__pb2._UUID
_PROAUDIENCELOOK_PROSCREENLOOK.fields_by_name['template_document_file_path'].message_type = basicTypes__pb2._URL
_PROAUDIENCELOOK_PROSCREENLOOK.fields_by_name['template_slide_uuid'].message_type = basicTypes__pb2._UUID
_PROAUDIENCELOOK_PROSCREENLOOK.fields_by_name['mask_uuid'].message_type = basicTypes__pb2._UUID
_PROAUDIENCELOOK_PROSCREENLOOK.containing_type = _PROAUDIENCELOOK
_PROAUDIENCELOOK.fields_by_name['uuid'].message_type = basicTypes__pb2._UUID
_PROAUDIENCELOOK.fields_by_name['screen_looks'].message_type = _PROAUDIENCELOOK_PROSCREENLOOK
_PROAUDIENCELOOK.fields_by_name['original_look_uuid'].message_type = basicTypes__pb2._UUID
DESCRIPTOR.message_types_by_name['ProAudienceLook'] = _PROAUDIENCELOOK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProAudienceLook = _reflection.GeneratedProtocolMessageType('ProAudienceLook', (_message.Message,), {

  'ProScreenLook' : _reflection.GeneratedProtocolMessageType('ProScreenLook', (_message.Message,), {
    'DESCRIPTOR' : _PROAUDIENCELOOK_PROSCREENLOOK,
    '__module__' : 'proAudienceLook_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.ProAudienceLook.ProScreenLook)
    })
  ,
  'DESCRIPTOR' : _PROAUDIENCELOOK,
  '__module__' : 'proAudienceLook_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.ProAudienceLook)
  })
_sym_db.RegisterMessage(ProAudienceLook)
_sym_db.RegisterMessage(ProAudienceLook.ProScreenLook)


# @@protoc_insertion_point(module_scope)
