# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proMask.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import slide_pb2 as slide__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proMask.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rproMask.proto\x12\x07rv.data\x1a\x0bslide.proto\";\n\x07ProMask\x12\"\n\nbase_slide\x18\x01 \x01(\x0b\x32\x0e.rv.data.Slide\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3'
  ,
  dependencies=[slide__pb2.DESCRIPTOR,])




_PROMASK = _descriptor.Descriptor(
  name='ProMask',
  full_name='rv.data.ProMask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_slide', full_name='rv.data.ProMask.base_slide', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='rv.data.ProMask.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=98,
)

_PROMASK.fields_by_name['base_slide'].message_type = slide__pb2._SLIDE
DESCRIPTOR.message_types_by_name['ProMask'] = _PROMASK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProMask = _reflection.GeneratedProtocolMessageType('ProMask', (_message.Message,), {
  'DESCRIPTOR' : _PROMASK,
  '__module__' : 'proMask_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.ProMask)
  })
_sym_db.RegisterMessage(ProMask)


# @@protoc_insertion_point(module_scope)
