# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proscreen.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import screens_pb2 as screens__pb2
import basicTypes_pb2 as basicTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proscreen.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fproscreen.proto\x12\x07rv.data\x1a\rscreens.proto\x1a\x10\x62\x61sicTypes.proto\"\xa9\x06\n\x12ProPresenterScreen\x12\x0c\n\x04name\x18\x01 \x01(\t\x12;\n\x0bscreen_type\x18\x02 \x01(\x0e\x32&.rv.data.ProPresenterScreen.ScreenType\x12(\n\x10\x62\x61\x63kground_color\x18\x06 \x01(\x0b\x32\x0e.rv.data.Color\x12\x1b\n\x04uuid\x18\x07 \x01(\x0b\x32\r.rv.data.UUID\x12 \n\x18\x62\x61\x63kground_color_enabled\x18\x08 \x01(\x08\x12K\n\x12\x61rrangement_single\x18\x03 \x01(\x0b\x32-.rv.data.ProPresenterScreen.SingleArrangementH\x00\x12O\n\x14\x61rrangement_combined\x18\x04 \x01(\x0b\x32/.rv.data.ProPresenterScreen.CombinedArrangementH\x00\x12R\n\x16\x61rrangement_edge_blend\x18\x05 \x01(\x0b\x32\x30.rv.data.ProPresenterScreen.EdgeBlendArrangementH\x00\x1a\x35\n\x11SingleArrangement\x12 \n\x07screens\x18\x01 \x03(\x0b\x32\x0f.rv.data.Screen\x1aV\n\x13\x43ombinedArrangement\x12 \n\x07screens\x18\x01 \x03(\x0b\x32\x0f.rv.data.Screen\x12\x0c\n\x04rows\x18\x02 \x01(\r\x12\x0f\n\x07\x63olumns\x18\x03 \x01(\r\x1aw\n\x14\x45\x64geBlendArrangement\x12\x14\n\x0cscreen_count\x18\x01 \x01(\r\x12 \n\x07screens\x18\x02 \x03(\x0b\x32\x0f.rv.data.Screen\x12\'\n\x0b\x65\x64ge_blends\x18\x03 \x03(\x0b\x32\x12.rv.data.EdgeBlend\"V\n\nScreenType\x12\x17\n\x13SCREEN_TYPE_UNKNOWN\x10\x00\x12\x18\n\x14SCREEN_TYPE_AUDIENCE\x10\x01\x12\x15\n\x11SCREEN_TYPE_STAGE\x10\x02\x42\r\n\x0b\x41rrangementb\x06proto3'
  ,
  dependencies=[screens__pb2.DESCRIPTOR,basicTypes__pb2.DESCRIPTOR,])



_PROPRESENTERSCREEN_SCREENTYPE = _descriptor.EnumDescriptor(
  name='ScreenType',
  full_name='rv.data.ProPresenterScreen.ScreenType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SCREEN_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SCREEN_TYPE_AUDIENCE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SCREEN_TYPE_STAGE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=770,
  serialized_end=856,
)
_sym_db.RegisterEnumDescriptor(_PROPRESENTERSCREEN_SCREENTYPE)


_PROPRESENTERSCREEN_SINGLEARRANGEMENT = _descriptor.Descriptor(
  name='SingleArrangement',
  full_name='rv.data.ProPresenterScreen.SingleArrangement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='screens', full_name='rv.data.ProPresenterScreen.SingleArrangement.screens', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=506,
  serialized_end=559,
)

_PROPRESENTERSCREEN_COMBINEDARRANGEMENT = _descriptor.Descriptor(
  name='CombinedArrangement',
  full_name='rv.data.ProPresenterScreen.CombinedArrangement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='screens', full_name='rv.data.ProPresenterScreen.CombinedArrangement.screens', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rows', full_name='rv.data.ProPresenterScreen.CombinedArrangement.rows', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='columns', full_name='rv.data.ProPresenterScreen.CombinedArrangement.columns', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=561,
  serialized_end=647,
)

_PROPRESENTERSCREEN_EDGEBLENDARRANGEMENT = _descriptor.Descriptor(
  name='EdgeBlendArrangement',
  full_name='rv.data.ProPresenterScreen.EdgeBlendArrangement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='screen_count', full_name='rv.data.ProPresenterScreen.EdgeBlendArrangement.screen_count', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='screens', full_name='rv.data.ProPresenterScreen.EdgeBlendArrangement.screens', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edge_blends', full_name='rv.data.ProPresenterScreen.EdgeBlendArrangement.edge_blends', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=649,
  serialized_end=768,
)

_PROPRESENTERSCREEN = _descriptor.Descriptor(
  name='ProPresenterScreen',
  full_name='rv.data.ProPresenterScreen',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rv.data.ProPresenterScreen.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='screen_type', full_name='rv.data.ProPresenterScreen.screen_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='background_color', full_name='rv.data.ProPresenterScreen.background_color', index=2,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='rv.data.ProPresenterScreen.uuid', index=3,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='background_color_enabled', full_name='rv.data.ProPresenterScreen.background_color_enabled', index=4,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arrangement_single', full_name='rv.data.ProPresenterScreen.arrangement_single', index=5,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arrangement_combined', full_name='rv.data.ProPresenterScreen.arrangement_combined', index=6,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arrangement_edge_blend', full_name='rv.data.ProPresenterScreen.arrangement_edge_blend', index=7,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PROPRESENTERSCREEN_SINGLEARRANGEMENT, _PROPRESENTERSCREEN_COMBINEDARRANGEMENT, _PROPRESENTERSCREEN_EDGEBLENDARRANGEMENT, ],
  enum_types=[
    _PROPRESENTERSCREEN_SCREENTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Arrangement', full_name='rv.data.ProPresenterScreen.Arrangement',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=62,
  serialized_end=871,
)

_PROPRESENTERSCREEN_SINGLEARRANGEMENT.fields_by_name['screens'].message_type = screens__pb2._SCREEN
_PROPRESENTERSCREEN_SINGLEARRANGEMENT.containing_type = _PROPRESENTERSCREEN
_PROPRESENTERSCREEN_COMBINEDARRANGEMENT.fields_by_name['screens'].message_type = screens__pb2._SCREEN
_PROPRESENTERSCREEN_COMBINEDARRANGEMENT.containing_type = _PROPRESENTERSCREEN
_PROPRESENTERSCREEN_EDGEBLENDARRANGEMENT.fields_by_name['screens'].message_type = screens__pb2._SCREEN
_PROPRESENTERSCREEN_EDGEBLENDARRANGEMENT.fields_by_name['edge_blends'].message_type = screens__pb2._EDGEBLEND
_PROPRESENTERSCREEN_EDGEBLENDARRANGEMENT.containing_type = _PROPRESENTERSCREEN
_PROPRESENTERSCREEN.fields_by_name['screen_type'].enum_type = _PROPRESENTERSCREEN_SCREENTYPE
_PROPRESENTERSCREEN.fields_by_name['background_color'].message_type = basicTypes__pb2._COLOR
_PROPRESENTERSCREEN.fields_by_name['uuid'].message_type = basicTypes__pb2._UUID
_PROPRESENTERSCREEN.fields_by_name['arrangement_single'].message_type = _PROPRESENTERSCREEN_SINGLEARRANGEMENT
_PROPRESENTERSCREEN.fields_by_name['arrangement_combined'].message_type = _PROPRESENTERSCREEN_COMBINEDARRANGEMENT
_PROPRESENTERSCREEN.fields_by_name['arrangement_edge_blend'].message_type = _PROPRESENTERSCREEN_EDGEBLENDARRANGEMENT
_PROPRESENTERSCREEN_SCREENTYPE.containing_type = _PROPRESENTERSCREEN
_PROPRESENTERSCREEN.oneofs_by_name['Arrangement'].fields.append(
  _PROPRESENTERSCREEN.fields_by_name['arrangement_single'])
_PROPRESENTERSCREEN.fields_by_name['arrangement_single'].containing_oneof = _PROPRESENTERSCREEN.oneofs_by_name['Arrangement']
_PROPRESENTERSCREEN.oneofs_by_name['Arrangement'].fields.append(
  _PROPRESENTERSCREEN.fields_by_name['arrangement_combined'])
_PROPRESENTERSCREEN.fields_by_name['arrangement_combined'].containing_oneof = _PROPRESENTERSCREEN.oneofs_by_name['Arrangement']
_PROPRESENTERSCREEN.oneofs_by_name['Arrangement'].fields.append(
  _PROPRESENTERSCREEN.fields_by_name['arrangement_edge_blend'])
_PROPRESENTERSCREEN.fields_by_name['arrangement_edge_blend'].containing_oneof = _PROPRESENTERSCREEN.oneofs_by_name['Arrangement']
DESCRIPTOR.message_types_by_name['ProPresenterScreen'] = _PROPRESENTERSCREEN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProPresenterScreen = _reflection.GeneratedProtocolMessageType('ProPresenterScreen', (_message.Message,), {

  'SingleArrangement' : _reflection.GeneratedProtocolMessageType('SingleArrangement', (_message.Message,), {
    'DESCRIPTOR' : _PROPRESENTERSCREEN_SINGLEARRANGEMENT,
    '__module__' : 'proscreen_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.ProPresenterScreen.SingleArrangement)
    })
  ,

  'CombinedArrangement' : _reflection.GeneratedProtocolMessageType('CombinedArrangement', (_message.Message,), {
    'DESCRIPTOR' : _PROPRESENTERSCREEN_COMBINEDARRANGEMENT,
    '__module__' : 'proscreen_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.ProPresenterScreen.CombinedArrangement)
    })
  ,

  'EdgeBlendArrangement' : _reflection.GeneratedProtocolMessageType('EdgeBlendArrangement', (_message.Message,), {
    'DESCRIPTOR' : _PROPRESENTERSCREEN_EDGEBLENDARRANGEMENT,
    '__module__' : 'proscreen_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.ProPresenterScreen.EdgeBlendArrangement)
    })
  ,
  'DESCRIPTOR' : _PROPRESENTERSCREEN,
  '__module__' : 'proscreen_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.ProPresenterScreen)
  })
_sym_db.RegisterMessage(ProPresenterScreen)
_sym_db.RegisterMessage(ProPresenterScreen.SingleArrangement)
_sym_db.RegisterMessage(ProPresenterScreen.CombinedArrangement)
_sym_db.RegisterMessage(ProPresenterScreen.EdgeBlendArrangement)


# @@protoc_insertion_point(module_scope)
