# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: targets.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2
import graphicsData_pb2 as graphicsData__pb2
import testPattern_pb2 as testPattern__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='targets.proto',
  package='rv.data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rtargets.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\x1a\x12graphicsData.proto\x1a\x11testPattern.proto\"\xf7\x01\n\tTargetSet\x12\x1b\n\x04uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1d\n\x05\x63olor\x18\x03 \x01(\x0b\x32\x0e.rv.data.Color\x12%\n\x0ftest_image_path\x18\x04 \x01(\x0b\x32\x0c.rv.data.URL\x12+\n\x0bsource_size\x18\x05 \x01(\x0b\x32\x16.rv.data.Graphics.Size\x12 \n\x07targets\x18\x06 \x03(\x0b\x32\x0f.rv.data.Target\x12*\n\x0ctest_pattern\x18\x07 \x01(\x0b\x32\x14.rv.data.TestPattern\"\xca\x02\n\x06Target\x12\x1b\n\x04uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x30\n\x10source_unit_rect\x18\x03 \x01(\x0b\x32\x16.rv.data.Graphics.Rect\x12\'\n\x0ftest_image_fill\x18\x04 \x01(\x0b\x32\x0e.rv.data.Media\x12(\n\x05shape\x18\x05 \x01(\x0b\x32\x19.rv.data.Graphics.Element\x12*\n\x08\x66lipMode\x18\x06 \x01(\x0e\x32\x18.rv.data.Target.FlipMode\"d\n\x08\x46lipMode\x12\x12\n\x0e\x46LIP_MODE_NONE\x10\x00\x12\x16\n\x12\x46LIP_MODE_VERTICAL\x10\x01\x12\x18\n\x14\x46LIP_MODE_HORIZONTAL\x10\x02\x12\x12\n\x0e\x46LIP_MODE_BOTH\x10\x03\x62\x06proto3'
  ,
  dependencies=[basicTypes__pb2.DESCRIPTOR,graphicsData__pb2.DESCRIPTOR,testPattern__pb2.DESCRIPTOR,])



_TARGET_FLIPMODE = _descriptor.EnumDescriptor(
  name='FlipMode',
  full_name='rv.data.Target.FlipMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLIP_MODE_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLIP_MODE_VERTICAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLIP_MODE_HORIZONTAL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLIP_MODE_BOTH', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=564,
  serialized_end=664,
)
_sym_db.RegisterEnumDescriptor(_TARGET_FLIPMODE)


_TARGETSET = _descriptor.Descriptor(
  name='TargetSet',
  full_name='rv.data.TargetSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='rv.data.TargetSet.uuid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='rv.data.TargetSet.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='rv.data.TargetSet.color', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_image_path', full_name='rv.data.TargetSet.test_image_path', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_size', full_name='rv.data.TargetSet.source_size', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='targets', full_name='rv.data.TargetSet.targets', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_pattern', full_name='rv.data.TargetSet.test_pattern', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=331,
)


_TARGET = _descriptor.Descriptor(
  name='Target',
  full_name='rv.data.Target',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='rv.data.Target.uuid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='rv.data.Target.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_unit_rect', full_name='rv.data.Target.source_unit_rect', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_image_fill', full_name='rv.data.Target.test_image_fill', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shape', full_name='rv.data.Target.shape', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flipMode', full_name='rv.data.Target.flipMode', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TARGET_FLIPMODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=664,
)

_TARGETSET.fields_by_name['uuid'].message_type = basicTypes__pb2._UUID
_TARGETSET.fields_by_name['color'].message_type = basicTypes__pb2._COLOR
_TARGETSET.fields_by_name['test_image_path'].message_type = basicTypes__pb2._URL
_TARGETSET.fields_by_name['source_size'].message_type = graphicsData__pb2._GRAPHICS_SIZE
_TARGETSET.fields_by_name['targets'].message_type = _TARGET
_TARGETSET.fields_by_name['test_pattern'].message_type = testPattern__pb2._TESTPATTERN
_TARGET.fields_by_name['uuid'].message_type = basicTypes__pb2._UUID
_TARGET.fields_by_name['source_unit_rect'].message_type = graphicsData__pb2._GRAPHICS_RECT
_TARGET.fields_by_name['test_image_fill'].message_type = graphicsData__pb2._MEDIA
_TARGET.fields_by_name['shape'].message_type = graphicsData__pb2._GRAPHICS_ELEMENT
_TARGET.fields_by_name['flipMode'].enum_type = _TARGET_FLIPMODE
_TARGET_FLIPMODE.containing_type = _TARGET
DESCRIPTOR.message_types_by_name['TargetSet'] = _TARGETSET
DESCRIPTOR.message_types_by_name['Target'] = _TARGET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TargetSet = _reflection.GeneratedProtocolMessageType('TargetSet', (_message.Message,), {
  'DESCRIPTOR' : _TARGETSET,
  '__module__' : 'targets_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.TargetSet)
  })
_sym_db.RegisterMessage(TargetSet)

Target = _reflection.GeneratedProtocolMessageType('Target', (_message.Message,), {
  'DESCRIPTOR' : _TARGET,
  '__module__' : 'targets_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.Target)
  })
_sym_db.RegisterMessage(Target)


# @@protoc_insertion_point(module_scope)
